#!/usr/bin/env node
// Generate the bilingual gallery, downloadable artifacts, and prompt index.
// --skip-render copies committed PNGs and needs no Chrome or npm dependencies.
import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { loadExamples, coverageReport } from '../skills/text2html2png/scripts/build-examples.mjs';
import { galleryPage, localize } from './gallery-page.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const docsDir = path.join(repoRoot, 'docs');
const skillDir = path.join(repoRoot, 'skills/text2html2png');

export function diagramDefinition(example, locale) {
  return {
    schemaVersion: 1, chart: example.chart, theme: example.theme,
    render: { width: example.width, padding: 24, scale: example.scale },
    data: example.fixtures[locale],
  };
}

export function promptsMarkdown(examples, coverage) {
  const lines = [
    '<!-- Generated by scripts/build-gallery.mjs. Edit the example .meta.json files instead. -->', '',
    '# Public example prompts', '',
    `${examples.length} examples covering ${9 - coverage.missingCharts.length}/9 chart types and ${5 - coverage.missingThemes.length}/5 visual themes.`,
    'All example content is synthetic. English and Chinese outputs use the same chart renderer.', '',
    'Browse the [English gallery](../../../docs/index.html) or [中文案例页](../../../docs/zh.html) for previews and downloads.', '',
    'The Diagram JSON downloads contain the complete versioned input for `scripts/render.mjs`. Natural-language prompts are interpreted by your agent and can produce different wording or grouping.',
  ];
  for (const example of examples) {
    lines.push('', `## ${example.title}`, '', `\`${example.chart}\` × \`${example.theme}\``, '');
    for (const locale of example.locales) {
      const copy = localize(example, locale);
      lines.push(`### ${locale === 'zh' ? '中文' : 'English'}`, '',
        `> ${copy.prompt.replaceAll('\n', '\n> ')}`, '',
        `[HTML](${example.id}-${locale}.html) · [PNG](../assets/gallery/${example.id}-${locale}-${example.theme}.png) · [Diagram JSON](../../../docs/examples/${example.id}-${locale}.diagram.json)`, '');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

export async function buildGallery({ skipRender = false } = {}) {
  const examples = await loadExamples();
  for (const example of examples) {
    example.fixtures = {};
    for (const locale of example.locales) {
      example.fixtures[locale] = JSON.parse(await readFile(example.fixturePathFor(locale), 'utf8'));
    }
  }
  const coverage = coverageReport(examples);
  await mkdir(path.join(docsDir, 'gallery'), { recursive: true });
  await mkdir(path.join(docsDir, 'examples'), { recursive: true });
  for (const example of examples) {
    for (const locale of example.locales) {
      const stem = `${example.id}-${locale}`;
      await copyFile(example.htmlPathFor(locale), path.join(docsDir, 'examples', `${stem}.html`));
      await writeFile(path.join(docsDir, 'examples', `${stem}.diagram.json`), JSON.stringify(diagramDefinition(example, locale), null, 2) + '\n');
      const pngPath = path.join(docsDir, 'gallery', `${stem}-${example.theme}.png`);
      if (skipRender) await copyFile(example.pngPathFor(locale), pngPath);
      else {
        const { renderScreenshot } = await import('../skills/text2html2png/scripts/screenshot.mjs');
        await renderScreenshot({ html: example.htmlPathFor(locale), out: pngPath, bg: 'auto',
          width: example.width, padding: 24, scale: example.scale, selector: '.wrap',
          chrome: null, allowNetwork: false, noSandbox: false, force: true });
      }
    }
  }
  await writeFile(path.join(docsDir, 'index.html'), galleryPage(examples, 'en'));
  await writeFile(path.join(docsDir, 'zh.html'), galleryPage(examples, 'zh'));
  await writeFile(path.join(skillDir, 'examples/prompts.md'), promptsMarkdown(examples, coverage));
  console.log(`Built English and Chinese galleries with ${examples.length} examples and complete HTML / PNG / Diagram JSON downloads.`);
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  buildGallery({ skipRender: process.argv.includes('--skip-render') }).catch(error => {
    console.error(error.message); process.exitCode = 1;
  });
}
